#!/bin/sh

# constants
JAVA_VERSION='openjdk-11.0.2'
PHP_VERSION='latest'
NODEJS_VERSION='12.13.0'

# setup xresources preferences
cp xresources/.Xmodmap ~
xmodmap ~/.Xmodmap

# setup i3 config preferences
cp i3wm/config ~/.i3
cp -rv i3wm/.scripts ~
sudo cp i3wm/i3status.conf /etc

# update pacman mirrors and first installs
sudo pacman-mirrors -f
sudo pacman -Syyu
sudo pacman -Sy yay maim xclip zsh qutebrowser curl alacritty the_silver_searcher ripgrep zathura

# setup alacritty
cp alacritty/.alacritty ~

# restart i3
i3-msg restart

# install vim and asdf
yay -Sy vim-git asdf-vm 

# setup asdf
adsf plugin-add nodejs
adsf plugin-add php
adsf plugin-add java

# install java
asdf install java $JAVA_VERSION
echo "export JAVA_HOME=$HOME/.asdf/installs/java/$JAVA_VERSION"

# install php
asdf install php $PHP_VERSION

# install nodejs
asdf install nodejs $NODEJS_VERSION

# setup zsh (ohmyzsh + zplug + config)
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
cp zsh/.zshrc ~
exec zsh

# setup vim (vim + vim-plug + plugins)
if [ ! -d ~/.vim ]; then mkdir ~/.vim; fi
mkdir -p ~/.vim/undodir
mkdir -p ~/.vim/plugged
cp vim/.vimrc ~
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim -c ':source ~/.vimrc'
vim -c ':PlugInstall'

# setup qutebrowser
cp -rv qutebrowser ~/.config
export BROWSER=''
xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
export BROWSER='/usr/bin/qutebrowser'
