#!/bin/sh

# setup xresources preferences
cp xresources/.Xmodmap ~
xmodmap ~/.Xmodmap

# setup i3 config preferences
cp i3wm/config ~/.i3
cp -rv i3wm/.scripts ~
sudo cp i3wm/i3status.conf /etc

# update pacman mirrors and first installs
sudo pacman-mirrors -f
sudo pacman -Syyu
sudo pacman -Sy yay maim xclip zsh qutebrowser curl alacritty the_silver_searcher ripgrep

# setup alacritty
cp alacritty/.alacritty ~

# restart i3
i3-msg restart

# install vim and asdf
yay -Sy vim-git asdf-vm 

# setup zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
cp zsh/.zshrc ~
exec zsh

# setup vim
if [ ! -d ~/.vim ]; then mkdir ~/.vim; fi
mkdir -p ~/.vim/undodir
mkdir -p ~/.vim/plugged
cp vim/.vimrc ~
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim -c ':source ~/.vimrc'
vim -c ':PlugInstall'

# setup qutebrowser
cp -rv qutebrowser ~/.config
